import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";

const customFont = localFont({
  src: "../public/fonts/awesome.regular.otf",
  variable: "--font-custom",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${customFont.variable} h-full antialiased`}
    >
      <body className="w-full min-h-full flex flex-col bg-waterloo text-colonial overflow-x-hidden">
        <Navbar />
        {children}
      </body>
    </html>
  );
}

